server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ai-learning-platform
  
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_learning_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Daya@2796}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  expiration: 86400000
  refresh-expiration: 604800000

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# Logging
logging:
  level:
    com.ailearning: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
    org.springframework.web: WARN

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
